apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: externaltasksmanager
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
    - name: storageAccount
      value: "sttaskstrackertsxfq7"
    - name: storageAccessKey
      value: "SAL7jM4YsbcFEaSE6nr6aHa0t5ZpsE005LKMCzcGyq2FPRsFzYMKqYG+B16lYQv6la4G36PLNVp9+AStCSMXEw=="
    - name: queue
      value: "external-tasks-queue"
    - name: decodeBase64
      value: "true"
    - name: route
      value: /externaltasksprocessor/process